### ISSUE TITLE
Publish to crates.io

### ISSUE THREAD

**Issue by msingle** [Freaky/rtss#1]
Saw this on lobste.rs, and tried to install with cargo. Are you planning to publish to crates.io?
I haven't done rust in the past, but if you plan on publishing, I can help figure out what to do to publish and give a pull request.

**Comment by Freaky** [comment]
Yep, still a bit rough around the edges for a crate but should get there shortly.  For the time being `cargo install --git https://github.com/Freaky/rtss.git` will have to do.

**Comment by Freaky** [comment]
https://crates.io/crates/rtss/0.3.0 \o/
